name: CI/CD workflow for Maven Build and Tomcat Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        working-directory: MyWebApp

      - name: List target files (check WAR file)
        run: ls -l target
        working-directory: MyWebApp

      - name: Deploy to Tomcat
        run: |
          WAR_FILE=target/MyWebApp.war
          curl -v --upload-file "$WAR_FILE" \
            --user "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
            "${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"
        working-directory: MyWebApp
